version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.0-alpine
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env
  
  backend:
      image: vitalian968/foodgram_backend:latest
      restart: always
      volumes:
        - static:/app/static/
        - media:/app/media/
      depends_on:
        - db
      env_file:
        - .env

  frontend:
    env_file: .env
    image: vitalian968/foodgram_frontend:latest
    command: cp -r /app/build/. /static/
    depends_on:
        - backend
    volumes:
      - static:/static
      
  nginx:
    image: vitalian968/foodgram_gateway:latest
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - frontend
    restart: always

